### ISSUE TITLE
Re-publish package as `cid` instead of `dart_cid` ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dart_cid#10]
At present this package is published as `dart_cid`:  https://pub.dev/packages/dart_cid
<img width="1156" alt="image" src="https://github.com/dwyl/dart_cid/assets/194400/adc0d729-6a16-4692-8568-fd3e219bf5db">

Meanwhile the `cid` package name is still available: https://pub.dev/packages/cid
<img width="933" alt="image" src="https://github.com/dwyl/dart_cid/assets/194400/3f458d30-e8f2-4b93-bfee-2d1b21a26412">

why didn't we just use that in the first place? 🤷‍♂️ 
if the `cid` name was "taken" I would _understand_ including "dart" in the name, 
but it doesn't make much sense to me to have it there if nobody `else` is using `cid` ... 🙃

**Comment by LuchoTurtle** [comment]
Unfortunately you can't delete/republish a package under a different name (https://stackoverflow.com/questions/17893867/how-to-rename-and-or-remove-a-pub-package).

Would it make sense to publish it as `dart` and make `cid_dart` point to `cid`, as suggested in the link above?

**Comment by nelsonic** [comment]
Sorry, Wasn't suggesting `deleting` the _existing_ one. 
Just publishing the **cid** package as there’s no reason to have “dart” in the package name. 🤞🏼

**Comment by LuchoTurtle** [comment]
While trying to publish the package as `cid`, I was prompted with this error.

```dart
Validating package... 
Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy

Do you want to publish cid 1.0.0 to https://pub.dev (y/N)? y
Uploading... (1.6s)
Package name `cid` is too similar to another active package: `ads` (https://pub.dev/packages/ads).
```

:|

Going to file an e-mail request, as per https://github.com/dart-lang/pub-dev/issues/4045. Cc'd y'all in it.

**Comment by nelsonic** [comment]
Good luck.🤞🏼
